name: Pull Request CI

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
<<<<<<< HEAD
=======
  push:
    branches:
>>>>>>> 866ac7a (removed test-reporter)
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out PR code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests
<<<<<<< HEAD
<<<<<<< HEAD
        run: ./gradlew test
=======
        run: ./gradlew clean test --no-daemon --stacktrace
>>>>>>> 866ac7a (removed test-reporter)
=======
        run: ./gradlew test
>>>>>>> db2bb18 (speed up tests, trying to fix pushing to ecr)
