name: CI

on:
  pull_request:
    branches:
      - master
      - development
  pull_request_target:
    branches:
      - master
      - development
  push:
    branches:
      - master
      - development

jobs:
  gradle-cli:
    runs-on: ubuntu-latest
    permissions:
      checks: write      # ✅ allows creating check runs
      pull-requests: write # ✅ needed if you want PR comments
      contents: read     # ✅ allows reading repo content
    steps:
      - name: Check out base repo code (not fork code)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew clean test --no-daemon --stacktrace

      - name: Test Reporter
        if: ${{ !cancelled() }} # run even if tests fail
        uses: dorny/test-reporter@v2
        with:
          name: Gradle Tests
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1

      - name: Log in to Amazon Public ECR
        run: |
          aws ecr-public get-login-password \
            | docker login --username AWS \
              --password-stdin public.ecr.aws

      - name: Build, tag, and push image to Public ECR
        env:
          ECR_ALIAS: ${{ secrets.ECR_PUBLIC_ALIAS }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=public.ecr.aws/$ECR_ALIAS/$ECR_REPOSITORY
          SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-7)
          
          docker build -t $IMAGE_URI:$SHORT_SHA .
          docker push $IMAGE_URI:$SHORT_SHA

          # Optional: also push "latest"
          docker tag $IMAGE_URI:$SHORT_SHA $IMAGE_URI:latest
          docker push $IMAGE_URI:latest

      - name: Show image URI
        run: |
          SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-7)
          echo "Published Image URI: public.ecr.aws/$ECR_ALIAS/$ECR_REPOSITORY:$SHORT_SHA"
