name: Pull Request CI

on:
  push:
    branches:
<<<<<<< HEAD
=======
      - development
  pull_request:
    branches:
>>>>>>> f554954 (fixes for ecr image versions and limit pushes to ecr to only master branch merges)
      - development
<<<<<<< HEAD
=======
      - master
  pull_request:
    branches:
      - development
<<<<<<< HEAD
=======
  push:
    branches:
>>>>>>> 866ac7a (removed test-reporter)
      - master
>>>>>>> 6a85867 (commented out release.yml, added master branch to test action)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out PR code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests
<<<<<<< HEAD
        run: ./gradlew test
=======
        run: ./gradlew clean test --no-daemon --stacktrace
>>>>>>> 866ac7a (removed test-reporter)
